version: 2
updates:
  # Config for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # Config for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
